# 
# docker-compose.yml — определяет сервисы для разработки и тестирования.

#Что нужно сделать:
#  - Настроить сервисы для:
#      - PostgreSQL (или MySQL) с начальной базой.
#      - Приложения Spring Boot (если нужно).
#  - Открыть нужные порты (например, 5432, 8080).
#  - Настроить volume для хранения данных БД.

version: '3.8'

services:
  # PostgreSQL база данных
  postgres:
    image: postgres:15
    container_name: bank_postgres
    environment:
      POSTGRES_DB: bank_db
      POSTGRES_USER: bank_user
      POSTGRES_PASSWORD: bank_user
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

# Хранилище данных (чтобы БД не сбрасывалась при перезапуске)
volumes:
  postgres_data: