#
# application.yml — главный конфигурационный файл Spring Boot.

#Что нужно сделать:
#  - Указать настройки подключения к базе данных.
#  - Указать порт приложения.
#  - Настроить параметры безопасности и JWT.
#  - Включить Swagger UI.


server:
  port: 8080             

spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/bank_db
    username: bank_user
    password: bank_user
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none   
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yml
    enabled: true

# Настройки JWT (придумайте свой секретный ключ, минимум 32 символа)
jwt:
  secret: секретный_ключ_длиной_не_менее_32_символов_12345
  expiration: 86400000          # Время жизни токена в миллисекундах (24 часа)

# Настройки Swagger (springdoc-openapi)
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
  api-docs:
    path: /v3/api-docs
    enabled: true
  show-actuator: true